const table = {
    tb_m_users: 'tb_m_users',
    tb_m_groups: 'tb_m_groups',
    tb_m_companies: 'tb_m_companies',
    tb_m_plants: 'tb_m_plants',
    tb_m_shop: 'tb_m_shop',
    tb_m_lines: 'tb_m_lines',
    tb_m_machines: 'tb_m_machines',
    tb_m_ledgers: 'tb_m_ledgers',
    tb_m_user_locations: 'tb_m_user_locations',
    tb_r_ledger_itemchecks: 'tb_r_ledger_itemchecks',
    tb_r_schedules: 'tb_r_schedules',
    tb_m_itemchecks: 'tb_m_itemchecks',
    tb_m_status: 'tb_m_status',
    tb_r_schedule_checker: 'tb_r_schedule_checker',
    tb_m_periodics: 'tb_m_periodics',
    tb_m_incharge: 'tb_m_incharge',
    tb_r_history_checks: 'tb_r_history_checks',
    tb_m_itemcheck_std: 'tb_m_itemcheck_std',
    tb_m_itemcheck_tools: 'tb_m_itemcheck_tools',
    tb_m_tools: 'tb_m_tools',
    v_generator_itemchecks: 'v_generator_itemchecks',
    v_schedules_monthly: 'v_schedules_monthly',
    v_tpm_findings: 'v_tpm_findings',
    tb_r_finding_checks: 'tb_r_finding_checks',
    v_tpm_history: 'v_tpm_history',
    tb_m_spareparts: 'tb_m_spareparts',
    tb_m_itemcheck_spareparts: 'tb_m_itemcheck_spareparts',
    tb_r_ledger_changes: 'tb_r_ledger_changes',
    tb_r_ledger_added: 'tb_r_ledger_added',
}


module.exports = table